### ISSUE TITLE
Incorrectly identifies Alpine Linux as Raspbian

### ISSUE THREAD

**Issue by sallas** [retrohacker/getos#67]
According to https://github.com/retrohacker/getos/blob/master/os.json#L9 only Raspbian can have the os-release file. Therefore when this file is encountered this  https://github.com/retrohacker/getos/blob/master/index.js#L62 assumes that since no other distro has been listed the disto has to be Raspbian.

Content of said os-release file:

NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.6.2
PRETTY_NAME="Alpine Linux v3.6"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"

**Comment by retrohacker** [comment]
Hi, is this still an issue for you?

**Comment by retrohacker** [comment]
This should be resolved in v3.1.1

**Comment by aviadmini** [comment]
Not resolved in 3.1.1 for `alpine-3.8` in docker

**Comment by guillemcanal** [comment]
@retrohacker It is still and issue unfortunately. 

I suspect that the [`os.json`](https://github.com/retrohacker/getos/blob/master/os.json#L10) is to blame here:

Most Linux distributions provides and `/etc/os-release` file  as explained [here](https://www.linux.org/docs/man5/os-release.html)

I suspect that `alpine-release` being placed bellow `os-release` in `os.json` cause this issue.

**Comment by iComputer7** [comment]
Just tested this with the alpine:edge image from the docker hub. It's still identified as Raspbian.

NodeJS version 12.2.0
GetOS version 3.1.1

/etc/alpine-release: `3.10_beta20190508`

/etc/os-release: 
```NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10_beta20190508
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"```

**Comment by Ierezell** [comment]
Hi, 

The problem still persists and Alpine is recognized as Raspbian (I think OpenSUSE is mistaken as raspbian as well).  
Is there any quick fix for that ? 

@guillemcanal does changing the order worked for you ? 

Have a great day.
